# Build worker image (VM template)
image: Visual Studio 2015

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  access_token:
    secure: lssbt7qseyxwc46940dj
  matrix:
    - nodejs_version: "6"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node prebuild.js

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
